name: Code Guidelines
# https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md#coding-rules

on: [push, pull_request]

jobs:
  build:

    name: Lint code

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - run: npm install

      - name: Run default npm tests
        run: npm test

      - name: Install t3kit Composer dependencies
        uses: docker://composer:1.9
        with:
          args: "install"

      - name: Run default Composer tests
        uses: docker://composer:1.9
        with:
          args: "run-script test"
